### ISSUE TITLE
Milestone 2 Goals

### ISSUE THREAD

**Issue by Murkantilism** [Murkantilism/Chromacore#2]
- New features implemented:
  - [x] Starting menu with options to chose levels **\- Completed 01/05**
  - [ ] Each level has it’s own unique music track
  - [ ] A smoother color transition between backgrounds **\- In-progress started  01/21**
  - [x] Pause functionality with option to quit to main menu **\- Completed 01/07**
  - [x] Basic navigation among menus **\- Completed 01/10**
  - [x] Convert x-position calculator from Python script to Unity code **\- Completed 01/07**
  - [x] Add 2D particle effect to Note pick-up **\- Completed 01/08**
  - [ ] Multiple characters??
- [x] Import music at runtime on PC for 2nd gamemode **\- Completed 01/17**
- [x] Import music at runtime on Android for 2nd gamemode **\- Completed 01/22**
