### ISSUE TITLE
Milestone 5.5

### ISSUE THREAD

**Issue by Murkantilism** [Murkantilism/Chromacore#62]
- [x] Implement in-app purchases
- [x] Implement screenshot functionality
- [x] Implement feedback from testers & Casper
