### ISSUE TITLE
Level Content QA Checklist

### ISSUE THREAD

**Issue by Murkantilism** [Murkantilism/Chromacore#65]
For all 20 levels, ensure the following items have been checked for quality and fairness:
- [x] Checkpoints are in good spots
- [x] There are plentiful and frequent checkpoints
- [x] That the EndOfLevel gameObject is at the end of the level
- [x] That all garbage is collected (unneeded assets are deleted to reduce filesize)
- [x] Play through each level once, to find props out of place, bugs, etc.
- [x] Check that MasterNotes have been assigned properly
